[2022-09-20T19:32:50.834+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: booking_ingestion.transform_data manual__2022-09-20T19:32:49.746230+00:00 [queued]>
[2022-09-20T19:32:50.840+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: booking_ingestion.transform_data manual__2022-09-20T19:32:49.746230+00:00 [queued]>
[2022-09-20T19:32:50.841+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-20T19:32:50.842+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-20T19:32:50.843+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-20T19:32:50.851+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): transform_data> on 2022-09-20 19:32:49.746230+00:00
[2022-09-20T19:32:50.854+0000] {standard_task_runner.py:54} INFO - Started process 805 to run task
[2022-09-20T19:32:50.856+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion', 'transform_data', 'manual__2022-09-20T19:32:49.746230+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_dag/main.py', '--cfg-path', '/tmp/tmpwc2xsjvd']
[2022-09-20T19:32:50.857+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask transform_data
[2022-09-20T19:32:50.859+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/data_ingestion_dag/main.py
[2022-09-20T19:32:51.008+0000] {task_command.py:384} INFO - Running <TaskInstance: booking_ingestion.transform_data manual__2022-09-20T19:32:49.746230+00:00 [running]> on host 3756ba1ca570
[2022-09-20T19:32:51.025+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:191: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-20T19:32:51.046+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=booking_ingestion
AIRFLOW_CTX_TASK_ID=transform_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-20T19:32:49.746230+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-20T19:32:49.746230+00:00
[2022-09-20T19:32:51.047+0000] {logging_mixin.py:117} INFO - Ingesting data for date: 2022-09-20 19
[2022-09-20T19:32:51.052+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_dag/main.py", line 38, in transform_data
    booking = pd.read_csv(f"{dag_path}/raw_data/{file_date_path}/booking.csv", low_memory=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/raw_data/2022-09-20/19/booking.csv'
[2022-09-20T19:32:51.059+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=booking_ingestion, task_id=transform_data, execution_date=20220920T193249, start_date=20220920T193250, end_date=20220920T193251
[2022-09-20T19:32:51.066+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 29 for task transform_data ([Errno 2] No such file or directory: '/opt/airflow/raw_data/2022-09-20/19/booking.csv'; 805)
[2022-09-20T19:32:51.112+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-09-20T19:32:51.130+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
